#ifndef AXOPENNDTPLUGIN_GLOBAL_H
#define AXOPENNDTPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef AXOPENNDTPLUGIN_LIB
# define AXOPENNDTPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define AXOPENNDTPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // AXMIMSLIB_GLOBAL_H
